POST http://localhost:3000/features
Content-Type: application/json

{
    "name": "TEST_FLAG",
    "description": "description",
    "enable": true,
    "projectId": "a23cce67-cea6-4f31-8e45-8ac0076ef4f8"
}
###

GET http://localhost:3000/projects/957c70f3-a438-4dc8-b22a-219d14b22e79/features
Content-Type: application/json
###

PUT http://localhost:3000/features/00493623-65e9-4cea-a535-218e7d66b941/change-flag
Content-Type: application/json

{
    "enable": false
}